# Generated by Django 5.1.7 on 2025-03-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Rule Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('rule_type', models.CharField(choices=[('velocity', 'Velocity'), ('amount', 'Amount'), ('location', 'Location'), ('card', 'Card'), ('device', 'Device'), ('behavioral', 'Behavioral'), ('aml', 'AML'), ('custom', 'Custom')], max_length=20, verbose_name='Rule Type')),
                ('condition', models.TextField(verbose_name='Condition')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('review', 'Flag for Review'), ('notify', 'Notify Only')], max_length=20, verbose_name='Action')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Risk Score')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('created_by', models.CharField(max_length=100, verbose_name='Created By')),
                ('last_modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Modified By')),
                ('applies_to_pos', models.BooleanField(default=True, verbose_name='Applies to POS')),
                ('applies_to_ecommerce', models.BooleanField(default=True, verbose_name='Applies to E-commerce')),
                ('applies_to_wallet', models.BooleanField(default=True, verbose_name='Applies to Wallet')),
                ('hit_count', models.IntegerField(default=0, verbose_name='Hit Count')),
                ('false_positive_count', models.IntegerField(default=0, verbose_name='False Positive Count')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='Last Triggered')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['rule_type'], name='rule_engine_rule_ty_9c4752_idx'), models.Index(fields=['is_active'], name='rule_engine_is_acti_f21c53_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Rule Set Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.CharField(max_length=100, verbose_name='Created By')),
                ('last_modified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Modified By')),
                ('rules', models.ManyToManyField(related_name='rule_sets', to='rule_engine.rule')),
            ],
            options={
                'verbose_name': 'Rule Set',
                'verbose_name_plural': 'Rule Sets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='Transaction ID')),
                ('triggered', models.BooleanField(default=False, verbose_name='Triggered')),
                ('execution_time', models.FloatField(verbose_name='Execution Time (ms)')),
                ('condition_values', models.JSONField(default=dict, verbose_name='Condition Values')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='rule_engine.rule')),
            ],
            options={
                'verbose_name': 'Rule Execution',
                'verbose_name_plural': 'Rule Executions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='rule_engine_transac_e2ae28_idx'), models.Index(fields=['triggered'], name='rule_engine_trigger_6f762e_idx'), models.Index(fields=['created_at'], name='rule_engine_created_f966fb_idx')],
            },
        ),
    ]
