# Generated by Django 5.1.7 on 2025-03-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='excluded_merchants',
            field=models.JSONField(blank=True, default=list, help_text='List of merchant IDs this rule does NOT apply to', verbose_name='Excluded Merchants'),
        ),
        migrations.AddField(
            model_name='rule',
            name='included_merchants',
            field=models.JSONField(blank=True, default=list, help_text='List of merchant IDs this rule applies to (if merchant_specific is True)', verbose_name='Included Merchants'),
        ),
        migrations.AddField(
            model_name='rule',
            name='merchant_specific',
            field=models.BooleanField(default=False, help_text='If enabled, this rule will only apply to the specified merchants', verbose_name='Merchant Specific'),
        ),
    ]
