# Generated by Django 5.1.7 on 2025-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_ecommercetransaction_response_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='country_code',
            field=models.CharField(default='US', help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='Country Code'),
        ),
    ]
