version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-transaction_monitoring}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./transaction_monitoring:/app/transaction_monitoring
      - static_volume:/app/transaction_monitoring/staticfiles
      - media_volume:/app/transaction_monitoring/media
      - log_volume:/var/log/transaction_monitoring

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-transaction_monitoring}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    restart: always
    command: celery -A transaction_monitoring.config worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-transaction_monitoring}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - db
      - redis
    volumes:
      - ./transaction_monitoring:/app/transaction_monitoring
      - log_volume:/var/log/transaction_monitoring

  celery-beat:
    build: .
    restart: always
    command: celery -A transaction_monitoring.config beat -l info
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-transaction_monitoring}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - db
      - redis
      - celery
    volumes:
      - ./transaction_monitoring:/app/transaction_monitoring
      - log_volume:/var/log/transaction_monitoring

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  log_volume: