# Generated by Django 5.1.7 on 2025-03-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Feature Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('data_type', models.CharField(max_length=20, verbose_name='Data Type')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('transformation', models.TextField(blank=True, null=True, verbose_name='Transformation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Feature Definition',
                'verbose_name_plural': 'Feature Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('model_type', models.CharField(choices=[('anomaly', 'Anomaly Detection'), ('classification', 'Classification'), ('behavioral', 'Behavioral Analysis'), ('network', 'Network Analysis'), ('adaptive', 'Adaptive Threshold')], max_length=20, verbose_name='Model Type')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('file_path', models.CharField(max_length=255, verbose_name='File Path')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Accuracy')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='Precision')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='Recall')),
                ('f1_score', models.FloatField(blank=True, null=True, verbose_name='F1 Score')),
                ('auc_roc', models.FloatField(blank=True, null=True, verbose_name='AUC-ROC')),
                ('training_date', models.DateTimeField(blank=True, null=True, verbose_name='Training Date')),
                ('training_data_size', models.IntegerField(blank=True, null=True, verbose_name='Training Data Size')),
                ('training_parameters', models.JSONField(default=dict, verbose_name='Training Parameters')),
                ('feature_importance', models.JSONField(default=dict, verbose_name='Feature Importance')),
                ('deployed_at', models.DateTimeField(blank=True, null=True, verbose_name='Deployed At')),
                ('deployed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deployed By')),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['model_type'], name='ml_engine_m_model_t_67a12a_idx'), models.Index(fields=['is_active'], name='ml_engine_m_is_acti_4fe380_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='Transaction ID')),
                ('prediction', models.FloatField(verbose_name='Prediction')),
                ('prediction_probability', models.FloatField(blank=True, null=True, verbose_name='Prediction Probability')),
                ('features', models.JSONField(default=dict, verbose_name='Features')),
                ('explanation', models.JSONField(default=dict, verbose_name='Explanation')),
                ('execution_time', models.FloatField(verbose_name='Execution Time (ms)')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_engine.mlmodel')),
            ],
            options={
                'verbose_name': 'ML Prediction',
                'verbose_name_plural': 'ML Predictions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='ml_engine_m_transac_3e6b86_idx'), models.Index(fields=['created_at'], name='ml_engine_m_created_ea221e_idx')],
            },
        ),
    ]
