# Generated by Django 5.1.7 on 2025-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
    ]
