# Generated by Django 5.1.7 on 2025-03-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpattern',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='transactionpattern',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='transactionpattern',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='transactionpattern',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Merchant ID'),
        ),
        migrations.AddField(
            model_name='transactionpattern',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='transactionpattern',
            name='related_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Related User ID'),
        ),
        migrations.AddField(
            model_name='transactionpattern',
            name='time_window',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Time Window'),
        ),
        migrations.AddField(
            model_name='transactionpattern',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AddField(
            model_name='transactionpattern',
            name='transaction_count',
            field=models.IntegerField(default=0, verbose_name='Transaction Count'),
        ),
        migrations.AlterField(
            model_name='amlalert',
            name='alert_type',
            field=models.CharField(choices=[('structuring', 'Structuring'), ('rapid_movement', 'Rapid Movement'), ('high_risk_jurisdiction', 'High Risk Jurisdiction'), ('round_amount', 'Round Amount'), ('multiple_transfers', 'Multiple Transfers'), ('circular_flow', 'Circular Flow'), ('party_connection', 'Party Connection'), ('round_amount_transactions', 'High Cumulative Round-Amount Transactions'), ('round_number_transfers', 'High Cumulative Round-Number Transfers'), ('identical_amount_transfers', 'Multiple Accounts Sending Identical Amounts'), ('multiple_transactions_between_accounts', 'Multiple Transactions Between Two Accounts'), ('other', 'Other')], max_length=50, verbose_name='Alert Type'),
        ),
        migrations.AlterField(
            model_name='transactionpattern',
            name='pattern_type',
            field=models.CharField(choices=[('structuring', 'Structuring'), ('round_amount', 'Round Amount'), ('rapid_movement', 'Rapid Movement'), ('circular_flow', 'Circular Flow'), ('cross_border', 'Cross Border'), ('high_risk_mcc', 'High Risk MCC'), ('round_amount_transactions', 'High Cumulative Round-Amount Transactions'), ('round_number_transfers', 'High Cumulative Round-Number Transfers'), ('identical_amount_transfers', 'Multiple Accounts Sending Identical Amounts'), ('multiple_transactions_between_accounts', 'Multiple Transactions Between Two Accounts'), ('other', 'Other')], max_length=50, verbose_name='Pattern Type'),
        ),
        migrations.AlterField(
            model_name='transactionpattern',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User ID'),
        ),
        migrations.AddIndex(
            model_name='transactionpattern',
            index=models.Index(fields=['merchant_id'], name='aml_transac_merchan_ca5ca0_idx'),
        ),
    ]
