# Generated by Django 5.1.7 on 2025-03-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Login Device ID'),
        ),
    ]
